apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sauce-connect.fullname" . }}
  labels:
    {{- include "sauce-connect.labels" . | nindent 4 }}
data:
  sauce-connect.yaml: |
  {{- $config := omit .Values.config "enabled" }}
  {{- toYaml $config | default "{}" | nindent 4  }}
  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
