apiVersion: v1
kind: Service
metadata:
  name: {{ include "sauce-connect.fullname" . }}
  labels:
    {{- include "sauce-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "sauce-connect.selectorLabels" . | nindent 4 }}
