---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sauce-connect-4.fullname" . }}
  labels:
    {{- include "sauce-connect-4.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.tunnelPoolSize }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sauce-connect-4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sauce-connect-4.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sauce-connect-4.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/srv/saucelabs/sauce-connect/sc-{{ .Values.image.tag }}-linux/bin/sc"]
          env:
            - name: SAUCE_REST_URL
              value: {{ .Values.sc.restUrl | quote }}
            - name: SAUCE_REGION
              value: {{ .Values.sc.region | quote }}
            - name: SAUCE_USERNAME
              value: {{ .Values.sc.user | quote }}
            - name: SAUCE_API_KEY
              value: {{ .Values.sc.accessKey | quote }}
            - name: SAUCE_STATUS_ADDRESS
              value: "0.0.0.0:{{ .Values.status.port }}"
            - name: SAUCE_TUNNEL_NAME
              value: {{ .Values.sc.tunnelName | quote }}
            - name: SAUCE_TUNNEL_POOL
              value: {{ .Values.sc.tunnelPool | quote }}
            - name: SAUCE_VERBOSE
              value: {{ .Values.sc.sauceVerbose | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: status
              containerPort: {{ .Values.status.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.status.liveness }}
              scheme: {{ .Values.status.scheme }}
              port: {{ .Values.status.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.status.readiness }}
              scheme: {{ .Values.status.scheme }}
              port: {{ .Values.status.port }}
            initialDelaySeconds: 4
            periodSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
