---
name: Test Helm Charts

on: pull_request # yamllint disable-line rule:truthy

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit tests
        uses: d3adb5/helm-unittest-action@v2
        with:
          helm-version: v3.8.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: helm lint charts/sauce-connect
