---
name: Test Helm Charts

on: pull_request # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit tests
        uses: d3adb5/helm-unittest-action@v2
        with:
          helm-version: v3.8.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: helm lint charts/sauce-connect
      - run: helm lint charts/sauce-connect-4
  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        k8s:
          - v1.27
          - v1.28
          - v1.29
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
